package goshdarnit

// profanityList contains a comprehensive list of profanities, slurs, and vulgarities
// for content moderation purposes. This list is used to build the Aho-Corasick automaton
// at package initialization time.
var profanityList = []string{
	// General profanity
	"fuck", "fucking", "fucked", "fucker", "fuckers", "fucks", "fuckhead", "fuckface",
	"fuckwit", "fuckwad", "fuckboy", "fuckboi", "fuckup", "fuckups", "fucktard",
	"motherfuck", "motherfucker", "motherfucking", "motherfuckers",
	"shit", "shits", "shitty", "shitting", "shitted", "shitstain", "shithead",
	"shitheads", "shitface", "shitfaced", "shithole", "shithouse", "shitbag",
	"bullshit", "bullshitting", "horseshit", "dipshit", "dumbshit", "apeshit",
	"damn", "damned", "damnit", "goddamn", "goddamned", "goddamnit",
	"hell", "hellhole",
	"ass", "asses", "asshole", "assholes", "asshat", "asswipe", "assface",
	"assclown", "jackass", "dumbass", "fatass", "lardass", "smartass", "hardass",
	"badass", "kickass", "candyass", "halfass", "halfassed",
	"bitch", "bitches", "bitchy", "bitching", "bitched", "sonofabitch", "sonuvabitch",
	"bastard", "bastards",
	"crap", "crappy", "crapping",
	"piss", "pissed", "pisses", "pissing", "pissoff",
	"whore", "whores", "whorish", "whorey",
	"slut", "sluts", "slutty", "slutbag",
	"skank", "skanky", "skanks",

	// Sexual terms
	"cock", "cocks", "cockhead", "cocksucker", "cocksucking", "cocksuckers",
	"cockblock", "cockface", "cockwomble",
	"dick", "dicks", "dickhead", "dickheads", "dickface", "dickwad", "dickweed",
	"dicknose", "dickbag", "dickless",
	"penis", "penises",
	"cunt", "cunts", "cunty",
	"pussy", "pussies", "pussycat",
	"vagina", "vaginas", "vag", "vajayjay",
	"twat", "twats", "twatwad",
	"tit", "tits", "titty", "titties", "titfuck",
	"boob", "boobs", "booby", "boobies",
	"cum", "cums", "cumming", "cumshot", "cumslut", "cumstain", "cumdumpster",
	"jizz", "jizzed", "jizzing",
	"wank", "wanker", "wankers", "wanking",
	"jerkoff", "jackoff",
	"blowjob", "blowjobs", "bj",
	"handjob", "handjobs",
	"dildo", "dildos",
	"buttfuck", "buttfucker", "buttfucking",
	"assfuck", "assfucker", "assfucking",
	"anal",
	"fellatio", "cunnilingus",
	"masturbate", "masturbation", "masturbating",
	"orgasm", "orgasmic",
	"erection", "boner", "boners", "hardon", "hardons",
	"horny", "horndog",
	"hump", "humping", "humped",
	"screw", "screwing", "screwed",
	"bang", "banging", "banged",
	"porn", "porno", "pornography", "pornographic",
	"smut", "smutty",
	"hooker", "hookers",
	"prostitute", "prostitutes",
	"pimp", "pimps", "pimping",
	"brothel", "brothels",

	// Racial slurs
	"nigger", "niggers", "nigga", "niggas", "negro", "negroes",
	"chink", "chinks", "chinky",
	"gook", "gooks",
	"jap", "japs",
	"spic", "spics", "spick", "spicks",
	"wetback", "wetbacks",
	"beaner", "beaners",
	"gringo", "gringos",
	"cracker", "crackers", "honky", "honkey", "honkies",
	"whitey", "whities",
	"kike", "kikes",
	"yid", "yids",
	"heeb", "heebs",
	"towelhead", "towelheads",
	"sandnigger", "sandniggers",
	"camel jockey", "cameljockey",
	"raghead", "ragheads",
	"paki", "pakis",
	"curry muncher",
	"wog", "wogs",
	"abo", "abos",
	"coon", "coons",
	"darkie", "darkies", "darky",
	"redskin", "redskins",
	"injun", "injuns",
	"squaw", "squaws",
	"zipperhead", "zipperheads",
	"slope", "slopes", "slopehead",
	"jigaboo", "jigaboos", "jiggaboo",
	"sambo", "sambos",
	"spearchucker", "spearchuckers",
	"porchmonkey", "porch monkey",
	"pickaninny", "picaninny",

	// Homophobic slurs
	"fag", "fags", "faggot", "faggots", "faggy",
	"homo", "homos",
	"queer", "queers",
	"dyke", "dykes", "dykey",
	"lesbo", "lesbos", "lezbo", "lezbos",
	"poofter", "poofters", "poof", "poofs",
	"fairy", "fairies",
	"pansy", "pansies",
	"queen", "queens",
	"sodomite", "sodomites",
	"buttboy", "buttboys",
	"cocksucker", "cocksuckers",
	"pillow biter", "pillowbiter",
	"fudgepacker", "fudge packer", "fudgepackers",
	"shirtlifter", "shirt lifter",
	"ass bandit",

	// Transphobic slurs
	"tranny", "trannies",
	"shemale", "shemales", "she-male",
	"ladyboy", "ladyboys", "lady-boy",
	"heshe", "he-she",
	"shim",
	"trap", "traps",
	"tgirl",

	// Ableist slurs
	"retard", "retards", "retarded", "tard", "tards",
	"spaz", "spazz", "spastic", "spazzy",
	"cripple", "crippled", "cripples",
	"mongo", "mong", "mongoloid",
	"idiot", "idiots", "idiotic",
	"moron", "morons", "moronic",
	"imbecile", "imbeciles",
	"cretin", "cretins",
	"lame", "lamer",
	"dumb", "dummy", "dummies",
	"psycho", "psychos",
	"lunatic", "lunatics",
	"insane",
	"schizo", "schizos",
	"nutjob", "nutjobs",
	"nutcase", "nutcases",
	"freak", "freaks", "freaky",
	"weirdo", "weirdos",

	// Body-shaming and other crude terms
	"fatso", "fatsos", "fattie", "fatties", "fatty",
	"tubby", "lardo", "porker", "porky",
	"uggo", "uglies", "fugly",
	"midget", "midgets",
	"dwarf", "dwarfs", "dwarves",
	"runt", "runts",
	"gimp", "gimps", "gimpy",

	// Anatomical crude terms
	"anus", "anuses", "arsehole", "arseholes", "arse", "arses",
	"ballsack", "ballsacks", "balls", "nutsack", "nutsacks", "nuts",
	"testicle", "testicles", "teste", "testes",
	"scrotum", "scrotums",
	"gooch", "taint", "grundle",
	"butthole", "buttholes", "buttcrack", "buttcheek", "buttcheeks",
	"rectum", "rectums",
	"foreskin",
	"clitoris", "clit", "clits",
	"labia",
	"pube", "pubes", "pubic",
	"pubis",
	"perineum",
	"ballsdeep",
	"deepthroat", "deep throat",

	// Compound and miscellaneous profanity
	"fuckoff", "fuck off", "fuckall", "fuck all",
	"shitload", "shitloads", "shitshow",
	"clusterfuck",
	"mindfuck",
	"clusterf",
	"wtf", "stfu", "gtfo",
	"milf", "milfs", "dilf", "dilfs",
	"gilf", "gilfs",
	"pawg",
	"thot", "thots",
	"rimjob", "rim job",
	"feltch", "feltching", "felch", "felching",
	"queef", "queefs", "queefing",
	"shart", "sharted", "sharting",
	"douche", "douches", "douchebag", "douchebags", "douchey", "douchy",
	"scumbag", "scumbags",
	"sleazebag", "sleazeball",
	"dirtbag", "dirtbags",
	"buttmunch", "butthead", "buttwipe",
	"assmunch", "arsemunch",
	"dickbreath",
	"shitbreath",
	"douchenozzle",
	"jizzface",
	"cuntface",
	"twatface",
	"fuckface",
	"dickweasel",
	"thundercunt",
	"cockwomble",
	"wankstain",
	"bellend", "bell end", "bellends",
	"knob", "knobs", "knobhead", "knobheads", "knobend",
	"tosser", "tossers",
	"minger", "mingers", "minging",
	"git", "gits",
	"sod", "sods", "sodding", "sodoff", "sod off",
	"bollocks", "bollock", "bollox",
	"bloody",
	"bugger", "buggers", "buggered", "buggery",
	"prat", "prats",
	"pillock", "pillocks",
	"plonker", "plonkers",
	"numpty", "numpties",
	"muppet", "muppets",
	"divvy", "divvies",
	"chav", "chavs", "chavvy",
	"pikey", "pikeys",
	"gypo", "gypos", "gyppo", "gyppos",
}
